import type { Metadata } from "next";
import "./../globals.css";
import { AppSidebar } from "@/components/AppSidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";



export const metadata: Metadata = {
    title: "Chat",
    description: "Generated by create next app",
};

export default function ChatLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <SidebarProvider>
                    <AppSidebar />
                    <main className="w-[100%] h-[100vh]">
                        <SidebarTrigger />
                        {children}
                    </main>
                </SidebarProvider>
                {/* {children} */}
            </body>
        </html>
    );
}
