import type { Metadata } from "next";
import AuthorizedGuard from "@/features/auth/authorizred-guard";

export const metadata: Metadata = {
    title: "Profile",
    description: "Generated by create next app",
};

export default function ProfileLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <AuthorizedGuard>
        
                    {children}
                </AuthorizedGuard>
            </body>
        </html>
    );
}
